### ISSUE TITLE
`createEmulator` fails if `emulator` package is missing

### ISSUE THREAD

**Issue by zner0L** [tweaselORG/andromatic#11]
I deleted the cache directory and wanted to create a new emulator with a clean installation, which produced the following error:

```
    Error: Command failed with exit code 1: /path/to/avdmanager create avd --name android11 --package system-images;android-30;google_apis;x86_64 
    --device pixel_4
    Error: "emulator" package must be installed!
    null
    [=========                              ] 25% Loading local repository...       
    [=======================================] 100% Fetch remote repository...       
    Auto-selecting single ABI x86_64
```

andromatic should install the package in `createEmulator` if it is missing.

**Comment by baltpeter** [comment]
I was confused how we could miss something so obvious and initially couldn't reproduce the problem. If I delete `~/.cache/andromatic`, `createEmulator` works just fine without your changes.

Turns out the problem is a little more subtle: It only occurs if you delete `~/.cache/andromatic/emulator` but already have the correct system image installed for the emulator you are trying to install.

In this case, you skip installing the system image here, which happens to also install the `emulator` package:

https://github.com/tweaselORG/andromatic/blob/2f5843db8266fbee8617549d354b0513761e9de1/src/emulator.ts#L91
